### PR TITLE
Don't say it obsoletes WHATWG URL Standard because it doesn't.

### PR DESCRIPTION
**Pull request by masinter**

### CODE REVIEW

**Comment by masinter** [comment]
This is just a "draft" PR -- I only got through the introduction.
Basically: don't try to **be** or **replace** or **obsolete** the WHATWG URL Living Standard.
I made edits to the intro to show you what I mean, but more changes are needed throughout the document.

**Comment by alwinb** [comment]
In contrast with the WHATWG standard itself with regards to RFC3986 and RFC3987 – I never use the word **obsolete**.  

I chose a title this bold because at the time of writing the WHATWG had been sidelining valid concerns about the quality of their standard for too long, at times in a way that was dismissive towards people whose expertise should have been recognised. 

I gave a key part of the solution to the technical problem the name of _forced resolution_ because that is exactly what the situation needed back then, not just on the technical level. Meaning has a way of exposing itself like that.

**Comment by alwinb** [comment]
The changes to the introduction are good, though I do not want to change _specification_ to _grammar_. Because of the above, but also technically it is not accurate. The grammar is only a small part. Reference Resolution, that is the main achievement.  

I had in mind to start with a new document to reconcile the RFCs and the WHATWG Standard. 

That project will certainly have a different title.

**Comment by masinter** [comment]
When you have N incompatible standards, introducing a new one often yields N+1 incompatible standards.
I think the word choice is essential. WHATWG and IETF both have different rules and practices for updating their specifications.
Even if your intent is to provide something that **could** be used as a replacement specification, there is more work to do before that can happen.  If you don't like calling it a Grammer, choose some other term. Even "Additional Specifications".
Maybe some day you might have different ways of describing URL resolution with QR codes and NFC tags and URL shorteners.  
People will adopt a path if they see an advantage over what they are doing now, and this how standards get stuck: you can't prove the advantage until it is adopted, which will not happen without proof or faith. This isn't personal, or "dismissive toward people" with unrecognized expertise.
Reconciling the RFCs and the WHATWG Standard will take many steps. People who are not reading this thread will need to agree on a plan of action. Perhaps we can schedule a "side meeting" at IETF and ask people to attend.
But for it to be productive it would be much better to have a document they could review; an Internet Draft has all the right legal stuff at the front.

**Comment by alwinb** [comment]
It does not say that it obsoletes the WHATWG standard. It embraces it, then provides a cleaner exposition. 

This is not an Internet Draft. It is a document that collects my research results from half a year ago. The situation was very different then.

I was preparing to write an Internet Draft, but I am starting to feel pushed. I'll do it when I have time and I still feel that it is the best way forward.

There's a few changes to the introduction and status in 0.7.1, loosely based on your suggestion.

Thank you,

**Pull request closed without merging**
